import { CourseModel } from "./models/course-model"
import { StudentModel } from "./models/student-model"
import { ScheduleModel } from "./models/schedule-model"
import { AttendanceModel } from "./models/attendance-model"

const STORAGE_KEY = "attendance_system_data"

// Datos iniciales del sistema
const initialData = {
  courses: [
    { _id: "1", code: "2DO_TEC_A", name: "2DO TEC A", level: 2, section: "A", createdAt: new Date().toISOString() },
    { _id: "2", code: "3RO_TEC_A", name: "3RO TEC A", level: 3, section: "A", createdAt: new Date().toISOString() },
    { _id: "3", code: "2DO_TEC_B", name: "2DO TEC B", level: 2, section: "B", createdAt: new Date().toISOString() },
    { _id: "4", code: "3RO_TEC_B", name: "3RO TEC B", level: 3, section: "B", createdAt: new Date().toISOString() },
    { _id: "5", code: "1RO_TEC_A", name: "1RO TEC A", level: 1, section: "A", createdAt: new Date().toISOString() },
    { _id: "6", code: "1RO_TEC_B", name: "1RO TEC B", level: 1, section: "B", createdAt: new Date().toISOString() },
  ],
  students: [
    // 2DO TEC A
    {
      _id: "s1",
      courseId: "1",
      listNumber: 1,
      firstName: "Juan",
      lastName: "Pérez",
      studentCode: "2024001",
      email: "juan.perez@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s2",
      courseId: "1",
      listNumber: 2,
      firstName: "María",
      lastName: "González",
      studentCode: "2024002",
      email: "maria.gonzalez@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s3",
      courseId: "1",
      listNumber: 3,
      firstName: "Carlos",
      lastName: "Rodríguez",
      studentCode: "2024003",
      email: "carlos.rodriguez@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s4",
      courseId: "1",
      listNumber: 4,
      firstName: "Ana",
      lastName: "Martínez",
      studentCode: "2024004",
      email: "ana.martinez@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s5",
      courseId: "1",
      listNumber: 5,
      firstName: "Luis",
      lastName: "López",
      studentCode: "2024005",
      email: "luis.lopez@example.com",
      createdAt: new Date().toISOString(),
    },
    // 3RO TEC A
    {
      _id: "s6",
      courseId: "2",
      listNumber: 1,
      firstName: "Pedro",
      lastName: "Sánchez",
      studentCode: "2023001",
      email: "pedro.sanchez@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s7",
      courseId: "2",
      listNumber: 2,
      firstName: "Laura",
      lastName: "Ramírez",
      studentCode: "2023002",
      email: "laura.ramirez@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s8",
      courseId: "2",
      listNumber: 3,
      firstName: "Diego",
      lastName: "Torres",
      studentCode: "2023003",
      email: "diego.torres@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s9",
      courseId: "2",
      listNumber: 4,
      firstName: "Sofia",
      lastName: "Flores",
      studentCode: "2023004",
      email: "sofia.flores@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s10",
      courseId: "2",
      listNumber: 5,
      firstName: "Miguel",
      lastName: "Vargas",
      studentCode: "2023005",
      email: "miguel.vargas@example.com",
      createdAt: new Date().toISOString(),
    },
    // 2DO TEC B
    {
      _id: "s11",
      courseId: "3",
      listNumber: 1,
      firstName: "Andrea",
      lastName: "Castro",
      studentCode: "2024006",
      email: "andrea.castro@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s12",
      courseId: "3",
      listNumber: 2,
      firstName: "Roberto",
      lastName: "Morales",
      studentCode: "2024007",
      email: "roberto.morales@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s13",
      courseId: "3",
      listNumber: 3,
      firstName: "Valentina",
      lastName: "Herrera",
      studentCode: "2024008",
      email: "valentina.herrera@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s14",
      courseId: "3",
      listNumber: 4,
      firstName: "Fernando",
      lastName: "Ruiz",
      studentCode: "2024009",
      email: "fernando.ruiz@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s15",
      courseId: "3",
      listNumber: 5,
      firstName: "Camila",
      lastName: "Jiménez",
      studentCode: "2024010",
      email: "camila.jimenez@example.com",
      createdAt: new Date().toISOString(),
    },
    // 3RO TEC B
    {
      _id: "s16",
      courseId: "4",
      listNumber: 1,
      firstName: "Andrés",
      lastName: "Mendoza",
      studentCode: "2023006",
      email: "andres.mendoza@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s17",
      courseId: "4",
      listNumber: 2,
      firstName: "Isabella",
      lastName: "Ortiz",
      studentCode: "2023007",
      email: "isabella.ortiz@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s18",
      courseId: "4",
      listNumber: 3,
      firstName: "Gabriel",
      lastName: "Silva",
      studentCode: "2023008",
      email: "gabriel.silva@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s19",
      courseId: "4",
      listNumber: 4,
      firstName: "Daniela",
      lastName: "Reyes",
      studentCode: "2023009",
      email: "daniela.reyes@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s20",
      courseId: "4",
      listNumber: 5,
      firstName: "Sebastián",
      lastName: "Paredes",
      studentCode: "2023010",
      email: "sebastian.paredes@example.com",
      createdAt: new Date().toISOString(),
    },
    // 1RO TEC A
    {
      _id: "s21",
      courseId: "5",
      listNumber: 1,
      firstName: "Natalia",
      lastName: "Vega",
      studentCode: "2025001",
      email: "natalia.vega@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s22",
      courseId: "5",
      listNumber: 2,
      firstName: "Javier",
      lastName: "Guzmán",
      studentCode: "2025002",
      email: "javier.guzman@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s23",
      courseId: "5",
      listNumber: 3,
      firstName: "Paula",
      lastName: "Navarro",
      studentCode: "2025003",
      email: "paula.navarro@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s24",
      courseId: "5",
      listNumber: 4,
      firstName: "Ricardo",
      lastName: "Campos",
      studentCode: "2025004",
      email: "ricardo.campos@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s25",
      courseId: "5",
      listNumber: 5,
      firstName: "Lucía",
      lastName: "Rojas",
      studentCode: "2025005",
      email: "lucia.rojas@example.com",
      createdAt: new Date().toISOString(),
    },
    // 1RO TEC B
    {
      _id: "s26",
      courseId: "6",
      listNumber: 1,
      firstName: "Mateo",
      lastName: "Cortés",
      studentCode: "2025006",
      email: "mateo.cortes@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s27",
      courseId: "6",
      listNumber: 2,
      firstName: "Emma",
      lastName: "Medina",
      studentCode: "2025007",
      email: "emma.medina@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s28",
      courseId: "6",
      listNumber: 3,
      firstName: "Nicolás",
      lastName: "Aguilar",
      studentCode: "2025008",
      email: "nicolas.aguilar@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s29",
      courseId: "6",
      listNumber: 4,
      firstName: "Martina",
      lastName: "Ríos",
      studentCode: "2025009",
      email: "martina.rios@example.com",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "s30",
      courseId: "6",
      listNumber: 5,
      firstName: "Santiago",
      lastName: "Peña",
      studentCode: "2025010",
      email: "santiago.pena@example.com",
      createdAt: new Date().toISOString(),
    },
  ],
  schedules: [
    // Horario Vespertino - Lunes
    {
      _id: "sch1",
      courseId: "5",
      dayOfWeek: 1,
      period: 1,
      startTime: "13:00",
      endTime: "13:40",
      subject: "ATENCIÓN A PPFF",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch2",
      courseId: "5",
      dayOfWeek: 1,
      period: 3,
      startTime: "14:20",
      endTime: "15:00",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch3",
      courseId: "5",
      dayOfWeek: 1,
      period: 4,
      startTime: "15:00",
      endTime: "15:40",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch4",
      courseId: "3",
      dayOfWeek: 1,
      period: 7,
      startTime: "17:20",
      endTime: "17:55",
      subject: "SOPORTE TECN.",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch5",
      courseId: "3",
      dayOfWeek: 1,
      period: 8,
      startTime: "17:55",
      endTime: "18:30",
      subject: "SOPORTE TECN.",
      createdAt: new Date().toISOString(),
    },
    // Horario Vespertino - Martes
    {
      _id: "sch6",
      courseId: "4",
      dayOfWeek: 2,
      period: 1,
      startTime: "13:00",
      endTime: "13:40",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch7",
      courseId: "4",
      dayOfWeek: 2,
      period: 2,
      startTime: "13:40",
      endTime: "14:20",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch8",
      courseId: "2",
      dayOfWeek: 2,
      period: 3,
      startTime: "14:20",
      endTime: "15:00",
      subject: "ACOMPAÑAMIENTO",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch9",
      courseId: "2",
      dayOfWeek: 2,
      period: 4,
      startTime: "15:00",
      endTime: "15:40",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    // Horario Vespertino - Miércoles
    {
      _id: "sch10",
      courseId: "3",
      dayOfWeek: 3,
      period: 1,
      startTime: "13:00",
      endTime: "13:40",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch11",
      courseId: "3",
      dayOfWeek: 3,
      period: 2,
      startTime: "13:40",
      endTime: "14:20",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch12",
      courseId: "1",
      dayOfWeek: 3,
      period: 3,
      startTime: "14:20",
      endTime: "15:00",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    // Horario Vespertino - Jueves
    {
      _id: "sch13",
      courseId: "5",
      dayOfWeek: 4,
      period: 1,
      startTime: "13:00",
      endTime: "13:40",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch14",
      courseId: "5",
      dayOfWeek: 4,
      period: 2,
      startTime: "13:40",
      endTime: "14:20",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch15",
      courseId: "3",
      dayOfWeek: 4,
      period: 5,
      startTime: "16:10",
      endTime: "16:45",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch16",
      courseId: "5",
      dayOfWeek: 4,
      period: 7,
      startTime: "17:20",
      endTime: "17:55",
      subject: "SOPORTE TECN.",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch17",
      courseId: "5",
      dayOfWeek: 4,
      period: 8,
      startTime: "17:55",
      endTime: "18:30",
      subject: "SOPORTE TECN.",
      createdAt: new Date().toISOString(),
    },
    // Horario Vespertino - Viernes
    {
      _id: "sch18",
      courseId: "6",
      dayOfWeek: 5,
      period: 1,
      startTime: "13:00",
      endTime: "13:40",
      subject: "SOPORTE TECN.",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch19",
      courseId: "6",
      dayOfWeek: 5,
      period: 2,
      startTime: "13:40",
      endTime: "14:20",
      subject: "SOPORTE TECN.",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch20",
      courseId: "6",
      dayOfWeek: 5,
      period: 3,
      startTime: "14:20",
      endTime: "15:00",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
    {
      _id: "sch21",
      courseId: "6",
      dayOfWeek: 5,
      period: 4,
      startTime: "15:00",
      endTime: "15:40",
      subject: "PROG. Y B. DATOS",
      createdAt: new Date().toISOString(),
    },
  ],
  attendance: [],
}

// Inicializar datos si no existen
export function initializeData() {
  if (typeof window === "undefined") return

  const stored = localStorage.getItem(STORAGE_KEY)
  if (!stored) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(initialData))
  }
}

// Exportar modelos para uso en la aplicación
export { CourseModel, StudentModel, ScheduleModel, AttendanceModel }
