-- Insertar los cursos disponibles
INSERT INTO courses (code, name) VALUES
  ('1RO_TEC_A', '1RO TEC A'),
  ('1RO_TEC_B', '1RO TEC B'),
  ('1RO_TEC_A_INFORM', '1RO TEC A INFORM'),
  ('1RO_TEC_B_INFORM', '1RO TEC B INFORM'),
  ('2DO_TEC_A', '2DO TEC A'),
  ('2DO_TEC_B', '2DO TEC B'),
  ('2DO_TEC_A_INFORM', '2DO TEC A INFORM'),
  ('2DO_TEC_B_INFORM', '2DO TEC B INFORM'),
  ('3RO_TEC_A', '3RO TEC A'),
  ('3RO_TEC_B', '3RO TEC B'),
  ('3RO_TEC_A_INFORM', '3RO TEC A INFORM'),
  ('3RO_TEC_B_INFORM', '3RO TEC B INFORM'),
  ('BRIGADA_PRIMERO_BGU', 'BRIGADA PRIMERO BGU-CIENCIAS C')
ON CONFLICT (code) DO NOTHING;
