-- Insertar estudiantes de ejemplo para cada curso
-- 2DO TEC A
INSERT INTO students (list_number, full_name, course_id) 
SELECT 1, 'ÁLVAREZ GARCÍA, MARÍA JOSÉ', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 2, 'BENÍTEZ LÓPEZ, CARLOS ANDRÉS', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 3, 'CASTRO MORALES, ANA LUCÍA', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 4, 'DELGADO PÉREZ, JUAN PABLO', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 5, 'ESPINOZA RAMÍREZ, SOFÍA ELENA', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 6, 'FERNÁNDEZ TORRES, DIEGO ALEJANDRO', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 7, 'GONZÁLEZ VEGA, VALENTINA ISABEL', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 8, 'HERNÁNDEZ CASTRO, MATEO SEBASTIÁN', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 9, 'JIMÉNEZ ORTIZ, CAMILA ANDREA', id FROM courses WHERE code = '2DO_TEC_A'
UNION ALL
SELECT 10, 'LÓPEZ SÁNCHEZ, DANIEL EDUARDO', id FROM courses WHERE code = '2DO_TEC_A'
ON CONFLICT DO NOTHING;

-- 3RO TEC A
INSERT INTO students (list_number, full_name, course_id) 
SELECT 1, 'MARTÍNEZ ROJAS, GABRIELA FERNANDA', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 2, 'NAVARRO SILVA, ANDRÉS FELIPE', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 3, 'ORTEGA MENDOZA, ISABELLA MARÍA', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 4, 'PAREDES GUZMÁN, SANTIAGO JOSÉ', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 5, 'QUINTERO VARGAS, DANIELA ALEJANDRA', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 6, 'RAMÍREZ FLORES, NICOLÁS DAVID', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 7, 'SALAZAR CRUZ, MARTINA SOFÍA', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 8, 'TORRES MEDINA, EMILIO ANTONIO', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 9, 'URRUTIA CAMPOS, VALERIA NICOLE', id FROM courses WHERE code = '3RO_TEC_A'
UNION ALL
SELECT 10, 'VÁSQUEZ REYES, LUCAS MATÍAS', id FROM courses WHERE code = '3RO_TEC_A'
ON CONFLICT DO NOTHING;

-- 1RO TEC A INFORM
INSERT INTO students (list_number, full_name, course_id) 
SELECT 1, 'ACOSTA BRAVO, EMILIA CAROLINA', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 2, 'BARRIOS LUNA, SEBASTIÁN IGNACIO', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 3, 'CORDERO PINTO, RENATA VICTORIA', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 4, 'DOMÍNGUEZ RÍOS, JOAQUÍN MANUEL', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 5, 'ESCOBAR NÚÑEZ, ANTONELLA BEATRIZ', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 6, 'FIGUEROA SOTO, MAXIMILIANO RAFAEL', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 7, 'GUERRERO IBARRA, CATALINA MERCEDES', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 8, 'HERRERA AGUILAR, BENJAMÍN ESTEBAN', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 9, 'IGLESIAS MORA, FLORENCIA CONSTANZA', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
UNION ALL
SELECT 10, 'JARAMILLO PEÑA, TOMÁS ALBERTO', id FROM courses WHERE code = '1RO_TEC_A_INFORM'
ON CONFLICT DO NOTHING;
